### ISSUE TITLE
difficult to reproduce

### ISSUE THREAD

**Issue by lianghao2000** [divyakraman/ECCV2022_FARFourierAerialVideoRecognition#1]
hello, I am trying to replicate your excellent work, but I'm encountering some issues. Using the given code, I can not achieve a similar top-1 accuracy on UAV-Human.

**Comment by divyakraman** [comment]
Hello, thank you for your interest in our paper. We've provided all hyperparameter details and weight initialization details in the paper. In case there are any other issues, please let us know the specific experiment and results you are having trouble with.
